### ISSUE TITLE
Images size in custom dataset

### ISSUE THREAD

**Issue by naserpiltan** [pavanvyn/Galaxy-classification#3]
Hi.
I'm trying to use Deep_SVDD with my own dataset.
As you said before , I made a csv file with these contents :
Location Label
/full/location/to/image_1.jpg 0
/full/location/to/image_2.jpg 0
/full/location/to/image_3.jpg 1
/full/location/to/image_4.jpg 2
/full/location/to/image_5.jpg 1
/full/location/to/image_6.jpg 0

But when i run this command : 
`python main.py ../log/galBarred/ ../data/train_test.csv ../data/apply_model.csv --objective one-class --train True --lr 0.0001 --n_epochs 100 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 100 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-6 --apply_model True --normal_class 0;`

I have this error :
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 309 and 371 in dimension 2 at /opt/conda/conda-bld/pytorch_1533739672741/work/aten/src/TH/generic/THTensorMath.cpp:3616`

Should i change the images size to special value ?
Thank you.

**Comment by pavanvyn** [comment]
Yes, you must convert them to 32 px x 32 px black and white images. If you
wish for a different image size, you need to chnage the NN.

Pavan

**Comment by naserpiltan** [comment]
@pavanvyn  Thank you for your answer.
I resized my images to 32*32 grayscale images.But now I have this error :
`RuntimeError: Given input size: (64x1x1). Calculated output size: (64x0x0). Output size is too small at /opt/conda/conda-bld/pytorch_1533739672741/work/aten/src/THCUNN/generic/SpatialDilatedMaxPooling.cu:69
`

**Comment by pavanvyn** [comment]
Hi, I am sorry it is very erroneous. To be honest, this was my first ML project and I worked on it for a couple of months only. I have not gone back to it since, so I am not really familiar with it anymore. I am afraid you will have to trace the error back yourself.

However, as I mention in my readme, the code is mostly from this repository - https://github.com/lukasruff/Deep-SVDD. I don't know if contacting the owner helps, but it is worth a try.

**Comment by naserpiltan** [comment]
@pavanvyn Thank you .
